version: '3'

services:
  node:
    image: 'node:10-alpine'
    container_name: node_container
    volumes:
      - './:/home/node/app'
    working_dir: '/home/node/app'
    ports:
      - '3000:3000'
    command: 'npm install && npm start'